version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: task_management_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: TEST
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: task_management_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://task_management_db:3306/TEST
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      database:
        condition: service_healthy

  test:
    build:
      context: .
      dockerfile: dockerfiletest
    container_name: task_management_test
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://task_management_db:3306/TEST
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  db_data:

